### ISSUE TITLE
Migrar para novo template

### ISSUE THREAD

**Issue by rgaiacs** [abelsiqueira/2016-08-01-ufpr#7]
Posso ajudar nisso se você quiser.

**Comment by abelsiqueira** [comment]
Quero ajuda sim. Não sabia nem de novo template. Tem guia de migração?

**Comment by rgaiacs** [comment]
> Quero ajuda sim.

:-)

> Não sabia nem de novo template.

https://github.com/swcarpentry/workshop-template/tree/2016-06

É para ser feito o merge em breve.

> Tem guia de migração?

Era para um git merge resolver mas como tem a traducão vai ser preciso resolver alguns conflitos.

**Comment by abelsiqueira** [comment]
Bom, se for ter muito conflito vai ficar à deriva. Ainda tenho bastante trabalho.

**Comment by fernandomayer** [comment]
@abelsiqueira se quiser faça o merge em outro branch e se der conflito eu vou resolvendo

**Comment by rgaiacs** [comment]
https://github.com/swcarpentry/workshop-template-pt-br
